1. 将条件变量阻塞放到队列中, 这样消费者也可以是生产者.   已经完成
2. 尝试自动调节线程大小, 如果是这样建议使用thread*, 这样增加和销毁产生的花销不大
3. 定义submit返回值类型, 使用using设置一个别名
3. 是否使用优先队列
4. 延时任务是否需要做一下?

支持多任务参数, 一切可调用对象都可以作为线程主函数执行
等待任务执行结果


使用bind会有性能的影响, 原因: 调用栈比较深


hashtable可能需要重新做一下, 安装接口来做. 不然都不成样子.
不行啊, 如果只是这样, 那么是不够的. 是否需要前进一步

* 就业困境
你首先需要认识到, 你已经27了, 你应该找工作了
你已经给过自己三个月了, 不能再给了
不能再这样下去了
别看你看了这么多小说, 以为自己很有知识, 但你不能立即想起来, 那就说明你没有. 
你现在这个情况, 是你没有做好, 怪不得别人. 很多人劝过你, 你也有很多机会, 不过是你没有珍惜而已.
跟你的天赋没有关系, 跟你的付出有关系, 跟你的积累有关系. 一直这么在意天赋, 一直想当个天才, 其实和心里一直有一种一夜暴富的想法和意识有关. 一年才能做好的东西, 恨不得一天就做完.奋斗五六年才能做到的, 恨不得两年做完. 所以学习也好, 做事情也好, 才会这样慌慌忙忙, 做事情顾头不顾尾, 才会才学习10分钟, 就想结束, 不看了呢, 又没有什么要干的呢? 自己毁灭自己.
概念有什么错呢? 用错了而已. 唯物和概念之间的关系.
不要做愤青, 社会父母都没有欠你什么.
我感觉靠编程养活自己是不可能了, 我不喜欢, 又不愿意投入时间
真正在上面花的时间, 连我玩的时间都没有.
精力不要分散. 做一件事就好, 不要想这想那的, 这也想做, 那也想做.
花钱, 花时间和花精力最多的地方, 你肯定比较擅长. 你可能不太愿意, 也不太喜欢, 但这已经成了事实了.

不要做电子仓鼠, 视频存下来不看, 收藏夹里落灰, 说明你不喜欢这件事情, 你不喜欢它里面的内荣, 你知识觉得很厉害, 或者你在假装我很厉害, 不要陷入这么虚假的幻境里面.
喜欢了, 你肯定迫不及待的去做, 如果你没有看过, 那么你最好不要收藏. 
很多道理知识都很不起眼, 不那么高大上, 也不那么抽象晦涩, 但理智和认知就是从这样不起眼, 很明显的地方慢慢的建立起来的.
如果一个网页, 一个视频, 你收藏起来, 你不看, 那说明不是必须的, 也不是你喜欢的. 那么就没有必要留着了
没有什么能一下解决你问题的神药, 药都是慢慢起作用的.
你没学好, 不怪别人.
把未来当成现在, 把或然当成必然. 这是你犯的又一个错误, 这甚至是你常犯的一个错误
所谓盛世, 就是把不可能变成可能, 万事万物都会发生强烈的难以想象的变化, 百年未有之大变局, 需要参与进去啊, 需要参与到项目当中, 需要参与到其中, 成为其中的一员.
有点感受和知道了是两码事, 知道了和去做是两码事, 做了和做成功了又是两码事.
你看, 知道了方法, 照着去做, 啥子和蠢货也能做好.

知识和学习知识的方法是不一样的. 知识和用知识的方法又是不一样的. 对知识的理解不能代替学习知识和使用知识的方法.
不能用对知识的理解代替学习知识的方法和使用知识的方法.

知识你往往会无意识的忽略, 只是因为它不能像夏天的冰泉水一样马上解渴吗. 你这就像是一个濒死的病人要一粒马上就能让他生龙活虎的丹药一样.

学习不能贪多, 需要好好的消化掉, 要精通, 精通的目的是为了应用.

学习问题要靠学习方法来解决，实践问题要靠动手来解决嘛

极尽升华什么的，要不得，不要被忽悠了
还每一阶段，这是死路
以为每一阶段做好就无敌了，实则是一种很死板的发展方式，只要能解决每一阶段的主要矛盾，结果就不会差
不是什么都记，就是根基扎实，基础，根基什么的不懂，也不需要懂。不要胡思乱想. 不要死记硬背.

太慢了
我在Linux上面消耗的时间过多, 本来是想得到一件锋利的武器, 最后反倒本末倒置, 忘记了初心, 耽误了太多的时间.
这样的错误犯过太多次了. 不能这样下去了, 即使是这个月, 做的事情太少了. 不能浪费时间啊.
想要将这些工具的厉害之处发挥出来, 必须得做事啊. 或者反过来说, 只有做事, 才可能发现这些优点.
使用不是目的, 用来做事才是目的. 
不能再晃晃悠悠的了, 必须充分利用手里的时间. 需要有点紧迫感. 不要用理由来安慰自己了.
不能在决策上面浪费太多的时间. 在关键的时候, 做点什么比什么都不做的要好.
很多时候, 照着目标前进, 做和目标强相关的事情, 哪怕进步很小, 坚持下来也会有效果,  反倒是"大跃进", 不但不能达到目的, 反倒有负面影响, 反倒是大倒退.

必须将哲学和具体学科分开. 数学哲学是哲学, 和数学有关, 但不能靠这个学习和研究数学.

在三观上, 在认识上, 一个很小的差异可能导致巨大的差别, 也可能导致及其巨大的错误

作为行为逻辑和思考逻辑基础的三观, 方法论等, 一定不能出现问题, 不然推演到最后的结论可能无法收场

不能忽略问题, 不能放任问题, 特别是关乎自己未来, 自己前途, 自己生死的问题, 不能拖, 一定不能拖, 否则可能发展到自己无论如何也不可能解决, 也来不及解决的问题. 开始的时候克制畏惧, 克制懒惰可能就能解决了, 最后可能再想解决, 再有能力也不可能解决了.

果然啊, 解决的问题的唯一办法就是一直去做, 不论身处什么样的状态, 不论是困倦还是精力充沛, 不论是深处绝望还是充满机会.

现在, 做什么不重要, 怎么做不重要, 结果是什么不重要, 状态怎么样不重要, 重要的是去做.

传授知识要简明扼要直白易懂

终究要学会珍惜

睡眠问题不解决，再大的雄心壮志都是镜花水月
再坚强的意志，都没用

事物的运行过程和运行结果相互联系，不可分离分离

安稳的地方会以更高的效率将自己的意志磨损，将自身的存在消融。

安稳的地方会以更高的效率将自己的意志磨损，将自身的存在消融。

人要是久不做主，慢慢地也不会做主了。

你的处境不是一时一事可以改变的, 需要很久很久才能改变. 不要恐惧得一件事情都不敢干, 也不要懒惰得想干一件事情就天翻地覆.

不要想着一件事情做完美, 不要想着将一件事情做得有所有优点, 这是要不得的, 这种想法的后果是迟迟下不定决心, 迟迟做不了事情.

一件事情达到目的就好, 不要想着尽善尽美, 特别是在你还没有能力的时候.

项目的主要内容还是得靠自己,  不要想着

想要凭空的写一个STL出来是不现实也不可能的, 这和你的能力没有关系, 关键在于你对STL的了解很有限, 这在 hashtable 之中表现的很明显了.
只有一种方法能完成这个项目, 那就是模仿. 靠着自己来解决问题, 并不意味着连最基本的信息都不了解, 连最基本的调查都不做.
自己一点点的从最原始的材料中得到一点点组件的信息, 然后整理出来, 然后组合, 实践, 完成. 这听起来高大上, 其实是愚蠢无比的, 特别是在有了别人整理出来的信息, 可以一次性获得所有的材料的情况下. 应该以最低的时间代价获取最多, 最全, 最准确的信息. 在这个STL项目中, 别人已经完成好的项目是最好的材料. 不要想着做点什么事情都要打上自己的印记, 任何时候都要特立独行, 不要想着自己经手的事物都必须独特, 我们必将使用别人的成果, 很多发展到现在的东西已经变得通用, 这意味着我们能理解并复原就好, 不要非要加点自己的东西进去. 自己经手的事物变得独特, 这应该是一个很自然的过程, 不要刻意, 当你自己独特的时候, 它们自然会变成你想要的样子因而独特. 学习事物(概念, 理论等)不应该总是想着有自己的独特理解, 容易造成曲解, 误解, 内涵外延就这样, 总是普遍而相似, 不应该为自己和别人相同相似而屈辱(笑), 不要总是想着要自己独特, 自己的理解和别人相似相同是正常的, 把握住真义, 自己就是正确, 而不是用和别人的理解相不相同来作为判断依据, 甚至标榜自己. 当有一天积累得足够, 自然会发生质变.
你对自己独立完成的理解太过极端, 人是不能自己一个人活在世上的. 这是不行的. 

十年时间啊, 看得都是写什么东西啊, 这些小说早就落后, 白白浪费了大好时光. 从中学到了什么呢? 什么都没有学到啊, 反倒是有了一身的臭毛病.

心理接受能力太差了. 一听接受不了, 头就埋沙子里面去了.



** 时间的问题
   毕业已经两年. 尚未有工作经历. 两年了啊, 如果是高中的话, 都过去一大半了. 


** 能力的问题
   学习过的很多内容已经忘记.
   面向对象的一些东西, 模板编程的一些东西. 排序算法, 数据结构
   还有一些东西没学: MySQL. 网络
   还有八股文.
   

** 态度的问题
   得过且过, 浑浑噩噩
   不把找工作当回事情

** 简历的问题
   尚未优化, 不够吸引人的


** 项目的问题:
须速战速决, 不可能等到全部写完了.
我必须先写一个可以说明的项目, 没写完, 那么就不放链接
投递简历, 检查意向. 投石问路.
之后做的就是完善简历, 同时想想沟通过程怎么说.
    1. 怎么说两年没有工作
    2. 怎么说项目的优缺点.
    3. 我对工作的报酬是什么.
    4. 背诵八股文, 数据结构和算法. 学习MySQL

*** 需要做
    unordered_map
    map
    string

**** 非必须, 有更好
    unordered_multimap
    unordered_set
    unordered_multset
    set
    map


*** 必须有的
    pair
    vector
    stack
    list
    queue
    string
    map
    hashtable
    sort
    string
    

*** 关于实现
    需要解决的问题:
        1. hashtable是怎么实现的? 是pair式的还是单个T, 如果是, 应该如何封装
           在unordered_map和unordered_multimap中, 声明使用 pair.
               1). STL 是如何用一个模板变量来代替pair的?
                   T是一个模板参数, pair 可以当成一个类型
               2). 既然只有一个模板变量来控制元素, 那么哈希值是如何得到的?
                   这里hash函数怎么实现的不重要, 重要的是如何调用的. 因为 hash 函数实现的必定是传入一个参数进去.
                   而这里需要解决的就是这个参数是怎么得来的, 这只能通过查看调用者才能实现.

                   这里需要注意insert_unique_noresize insert_multi_noresize erase  这两个函数. 调用了hash函数

                   这些参数是什么, 如何能够得到哈希值. 
                   const auto n = hash(value_traits::get_key(value));
                   hash(value_traits::get_key(first.node->value))


                   erase_unique(const key_type& key) 中, key_type 又是什么? 可以通过   const auto n = hash(key); 来调用 hash函数

                   

                   什么? 居然是T? 只有一个模板参数?
               哈希值来自两个方面, 要么%n, 要么%桶的数量.
               3). 对于选择哪种数据结构, 我要考虑两点:
                   a. 实现是否完整
                   b. api接口
               4). 必须知道哪些函数是必须的. 必然会用到的.
        2. 它的接口是如何设计的, 让undorder_map和undorder_multimap都可以使用?
           其余所有的东西都是使用 hashtable 的接口实现的. 现在重点在hashtable上面
        3. hash 函数如何设计的, rehash函数又如何设计的?
           对于浮点数是否可以使用通用哈希函数来做呢? 诸位哈希的办法虽然就在这里, 但属实有点看不懂.
           而且我也不想和别人一模一样. bitwise_hash
        4. 如果是multi和map同一个底层数据结构, 那么需要在此数据结构中准备好multi和map
        5. 使用vector容器, 好扩展
        使用的接口, 而且需要注意的是, 它们的接口是不一样的.

        6. 需要的接口 
           1)hash函数
           2)rehash
           3)size
           4)clear
           5)insert
           6)erase

    unordered_map, 不去管具体实现了, 反正都需要封装, 看看怎么封装才好.
    找一个实现比较详细完全的, 抄也好抄一点.

类中的插入函数:
    hashtable<T, Hash, KeyEqual>::                        ==>
    insert_unique_noresize(const value_type& value)
    const auto n = hash(value_traits::get_key(value));


类: 
    template <class T, class Hash, class KeyEqual>
    class hashtable:

    typedef ht_value_traits<T>                          value_traits;       ==>
    typedef typename value_traits::key_type             key_type;


调用的类:
    template <class T>
    struct ht_value_traits

    typedef ht_value_traits_imp<T, is_map> value_traits_type;
 
    typedef typename value_traits_type::key_type    key_type;
 
    template <class Ty>
    static const key_type& get_key(const Ty& value)                          ==>
    {
      return value_traits_type::get_key(value);
    }

调用的类:

    template <class T>
    struct ht_value_traits_imp<T, true>
    {
      typedef typename std::remove_cv<typename T::first_type>::type key_type;
      typedef typename T::second_type                               mapped_type;
      typedef T                                                     value_type;
    
      template <class Ty>
      static const key_type& get_key(const Ty& value)
      {
        return value.first;
      }

 
草了, 原来是一开始就使用了pair, 写那么多层干什么, 好玩啊?


| 平方探测法                                  | 杜鹃散列     |                                                |
|---------------------------------------------+--------------+------------------------------------------------|
| 查找平均花费O(1), 最坏log N / (log log N)   | 最多两次查找 | 有可能有元素不能插入                           |
| 惰性删除                                    | 不用惰性删除 | 对哈希函数太过敏感,并不通用,缺点和优点一样明显 |
| 表大小不是素数, 装填因子大于0.5可能无法插入 |              |                                                |
|                                             |              |                                                |
不能的话, 只能看看人家怎么写的了, 搞亮点真不容易.
杜鹃散列和跳房子散列只能放弃.
修修改改, 找个亮点, 面试的时候有的聊.
通用散列函数可以试试. 其他的没有亮点, 找个这个亮点看看.

分离连接法的缺点: 创建新节点需要时间, 实现需要另外一种数据结构
平方探测法的缺点: 创建的空间只能一半能用, 删除的实现很麻烦


*** 要做的东西
1. 需要用什么样的方法来避免冲突(线性探测法)
2. 需要使用什么样的哈希函数
3. 有哪些接口
4. 需要迭代器吗?



*** MySTL要求: 
	1. 需要能编译通过
	2. 需要测试接口
	3. 可能需要添加一些东西, 比如map封装了红黑树, 那么我们是否可以将红黑树封装成map?(非必须)
    4. 对于排序算法, 可以用一下我写的测试框架.稍微改一下, 增加一点代码量.
    

*** MySTL问题
现在的问题:
	1. 如果需要修改, 那么很难
	2. 过去的时间太长了, 很多东西不记得了.
	3. 内容很杂, 而课本又没有详细解释
    4. STL有些什么, 需要做什么, 不需要做什么, 不清楚

优点:
	1. 我做了vector, list. 






***
1. 编程风格不一样, 这一看就是抄的.
2. 代码的行数不一样, 一个几百行, 一个上千行, 这怎么可能呢?
3. 

* 尝试
我今年年初的时候尝试
结果: 失败
失败的原因: 偷懒, 不敢去做.
            有时候明明问题就在哪里, 害怕, 不敢去碰
            不论是看小说, 摆弄Linux都是一种逃避的手段.

一直拖着, 我有了个问题, 不去解决, 以为要解决某某问题才能继续走下去, 最后呢? 自己也没有解决这个问题, 然后就这样拖着了. 
本来可以马上解决的问题, 非要写看小说, 打字, 激情磨尽, 然后就一直拖下去了.


* 关于这三个月来的反思

** 目标
只可惜我一直目的不明, 没有明确的目的, 又怎么会有坚定的信念和不懈的坚持呢?
很多事情真的不是做着做着就云开雾见明的, 反倒是越做越糊涂. 我就是太糊涂了, 所以停了下来, 可惜还是没有明白.
一开始就没有想清楚, 可惜到了这个地步, 我已经没有反悔的余地了. 

** 社会
我完全不知道哪些东西重要, 哪些东西不重要, 自己应该做些什么.
这也许是因为父母口中的脱离社会太久了?
以前三天就可以做的事情, 现在拖半个月才能做好
以前一个星期就可以做的事情, 现在需要一个月
也许就是我离开社会太久了

** 习惯问题
懒惰 精力不足, 睡眠不够, 怎么又有活力去做事情呢? 所以看起来才懒懒散散
没有就业意向
没有危机感, 手里有钱就狂欢

** 作息问题
为了避免思考未来, 你宁愿看小说熬夜, 也不愿尝试一下. 熬夜之后也没有精力去处理事情, 恶性循环
也许, 睡觉也是一种逃避
自4月到6月的这两个月的时间, 可以说, 我的作息完全崩溃了.

** 性格问题
浪费了时间, 错过了时机, 不想着弥补和挽救, 反到自甘堕落, 自暴自弃, 得过且过

** 时间和职业规划
完全没有把握时机的觉悟
完全封闭自己, 封闭信息来源, 躲在自己的世界里, 拆掉自己爬出深渊的梯子取火

** 思想上的问题
线性的做事情, 这是十年来最明显的, 却也是最不容易发现的问题.
只有一件事做好了才做一件事, 如果阻塞了, 就死磕一件事情. 做事情是这样, 学习也是这样.
这样做, 会有安全感, 会有爽感, 自己心里也舒服. 但就是不能做成事情, 十年的经验教训告诉我了.
可学习结果不受意志控制, 那么有没有安全感都是一样的, 只不过过程有点差别, 结果好就行了. 
这是不对的, 一件事情陷入了僵局, 那么就做另一件事情. 以此类推, 总有能做的.

** 心理问题
想着一来就选个好工作, 但学历和能力是不支持的, 忽视了自身的条件
但我真的不希望, 一辈子就是发快递, 电子厂. 做了什么就是什么样的人. 我怕我到时候脱不开身. 走不出去.
父亲太天真, 哪有老板不榨干你的时间的? 至少十天的工作经验是这样的.
我有机会没把握住和没有这个条件是两回事情.
害怕就业

** 金钱
自己对金钱的使用没有概念, 或者说, 拒绝接受这个事实.
花钱没度

** 机会
你有那么多次认清现实的机会, 却不承认, 宁愿将头埋在沙子里面, 不承认却又无法证明
很多时候你知道了问题, 也知道怎么解决, 但是却置之不理, 似乎一切都会好起来, 但事实却并非这样.

** 生理问题
长达十年时间的熬夜, 撸管, 大大损害了我的生理成长, 生理健康, 心理健康. 而且, 这一切的损害是不可逆的.
其实, 这才是我心底最在意的, 其他的我都可以说我还有机会, 唯独这个, 再无机会.
而这个是所有所有的基本条件, 是所有所有中的基础. 伤到了根基.
只有有眼睛的人才能画画, 只有喉咙完好的人才能歌唱, 只有有脚的人才能登高, 只有有手的人才能托举.
我现在很难在一段时间之内集中注意力了, 反倒是非常容易走神, 做着做着, 思维停滞了, 呆呆的, 连时间流逝都不知道, 真成呆若木鸡了.



** 6月错误
这半个月我还是犯了欲速则不达的错误，想着什么都要一天完成，这是我自己没法做到的事情

想要一天做完，就要休息足够，状态要好，知识准备充足，但是都没有办法完成，所以产生焦虑，想早睡，失败之后更焦虑，最终时间付与B站和小说，完全失败，判断是好的，但没有现实实现的条件

战国愈是到后期，六国愈是想一次覆灭秦国，愈是幻想

从此之后，不论是数学还是生活，不论是编程还是前途，我都要自己决定自己的轨迹了

我放弃激进的计划了，秦奋六世而统一天下，我呢，总不可能一次就做好吧？

以后我的路真的得自己走了，自己的主意自己拿

不再拒绝正确的事情
不再拒绝正确
把自己转到正确的地方来，实践！实践！
想要短时间内完成是不可能了

** 


我不想再骗了，理由和借口我编得足够多了，累了，我也不想再受制约了

想想自己要去哪里

该自立了

编程不是玩，不是随随便便就可以学会的

没有勇气，没有自信，可能是缺少实践的缘故，十年来，多思少做，结果并不好，鼓起勇气，去做点什么吧
一个帝王最重要的就是自信，只要有了自信，心胸就会宏大无比

了解，才能制定对策，需要理性，不要再感性了

感情是奢侈的东西，建立在物质之上

如何变强？唯交流实践，取长补短
他们能变强，我也能

不过是按照正确的方式，得到正确的结果而已
日积月累，方有此等结果

别看我抽烟, 时不时吃上只烤鸭, 感觉很贵, 花销很大, 其实真正贵的, 真正花销大的, 是没有找到工作, 没有达到自己的目的, 为此而付出的代价才是最贵的, 比如心态崩溃而自暴自弃的时间, 放弃了机会放纵自己的, 花在Linux上面的时间(这其实也是一种自我放纵的方式). 加起来有一两个月, 而每月的花销有多少呢? 差不多有3000 , 也就是说, 我浪费了将近6千, 这其实才是最浪费的, 最贵, 最不值得的. 什么都没有做, 就这样了. 烤鸭什么的, 不是什么贵的. 要是真的想节省, 那就只能尽快找到工作. 

学习的时候, 不要有意无意的扭曲你学的知识, 它说什么就是什么.

有种老师没有教, 我不用学的感觉, 不强迫就不去学习, 就做睁眼瞎, 真理不真理无所谓, 当不存在, 这不行啊.
教的时候呢, 故意扭曲, 要从鸡蛋里面找出恐龙来, 又不认真听, 非要搞自己那一套. 怕学习的困难, 非得想着给自己找一个捷径走一走.
换句话说怎么样都不学, 非得自己创造, 很有民科味.
在需要自学的时候, 我总是需要(实际是想)证明这证明那的, 只有证明了之后才能去做, 这是为什么, 我感觉是这样的, 我缺乏对这个世界基本的认知, 理解不了一些底层的逻辑, 我求诸于哲学. 但有时又会想, 也许没有这么复杂, 也许我只是不想努力研究又怕人家看出来, 所以做些别人都不理解的事情来掩饰. 没有做任何事情的动机和兴趣.

靠自己摸索是不可能成功的, 绝不可能

难的事情能做到，简单的事情也能做到，这是显而易见的事情，可我给自己设置得太难，太重，压得时间太长，就像久压的弹簧，失去了活性


折腾这么久, 还是其他人都不接触, 不知道的小众的东西, 其实就是想说明我比其他人差, 想有个证明, 但事实是, 我也是一个普通人. 同时也说明了我没有信心和勇气和其他人竞争, 哪怕是很普通的领域. 所以我奢望在很难的地方证明自己, 但事实证明这是一个错误的决定.
你要付出多少时间多少的精力来弥补你这些年来和其他人的差距, 你需要多么坚强的意志, 多么正确的决定, 多么难耐的坚持, 才能追上去?
不要好高骛远, 先从简单的做起, 先易后难, 循序渐进. 定太高了, 够不着的. 
你一直看不起你的学校, 连带着人都懒得理, 可你是否知道, 人家六百多分的都可以进去, 你为什么就不能学学人家, 积极向上一点呢?

填报志愿, 选择学校和专业, 你的父母没有干涉你, 只是让你自己选. 你还有什么好抱怨的? 这都是你自己决定的啊, 自己的选择啊. 大学父母可曾亏待过你? 没有吧? 毕业了, 父母养了你两年, 你又如何? 满嘴谎言, 你还不知足吗?

母亲父亲帮了你不少了, 不要再找他们了.

你所认知的出轨, 3p, 绿帽的都是些什么人? 你自己不知道吗? 成天在网上抱怨发火的人是什么人, 你自己也不知道吗? 多是写中专技校的吧? 大学的, 硕士的, 博士的有没有, 有, 还不少, 但是占多少比例呢?

出色的人不一定是清北复交, c9, 985的, 但里面出来的大多是出色的. 

跟着一些混混混, 是没有出路的.

你是一点都不重视啊, 父母的血汗付出关心, 你当成什么了? 你就那样踩在脚下? 漠不关心? 这是你对自己的不负责, 对未来的不负责, 对父母的不负责.

既然你所求的结果是那样, 过去已经无法改变了, 那么为什么不直接追求结果呢? 放弃过去吧. 求名利, 人之性也, 没有必要打压自己的想法, 没必要自己非要怎么怎么样. 反对自己本真的想法, 自己不开心, 而且还不一定得到好结果.

追求荣誉是好的, 但是不能虚荣.

不能什么都怪罪在自己父母的头上.

不要扭曲自己的认识, 不论是故意的, 还是无意的. 不能封闭自己的耳目, 不能拒绝外界的信息.

有需要才去准备, 而不是准备好了才去做.

做事不要硬拼, 讲究战略战法, 讲究方式方法, 得到我们想要的结果, 万人敌都是这样做的. 任何想完成计划任务, 任何想取得胜利成功的人都是这样想, 也是这样做的. 别被小说给骗了, 什么两方战斗道痕都被磨灭了呀之类的, 上来就是莽, 不动脑子, 脑子都用来所谓的悟道了, 之类的, 全是鬼话, 骗人的. 作者有多高的智商, 有多少的智慧,如何的布局, 全在作品里展现出来了. 不过像遮天里人物的英雄气概和宏伟的理想倒是值得学习.

掌握了方法, 在合适的地方用了合适的方法, 那就是聪明人, 也就是说聪明人就是擅长使用方法的人. 人们的生理上的差异真的有那么大吗? 恐怕不是. 诺伊曼爱吃糖, 有的人头大, 有的人头小. 硬要研究爱因斯坦大脑皮层神经层面的细节反倒会走上了邪路, 反倒走上了唯心主义的道路, 这个唯心主义不是"神", 不是"意识"和"精神", 而是生下来就有的"天才", 且这个天才别人无论如何也比不过. 所谓"天才", 别人打败的例子恐怕有很多, 斯密顿恐怕是一个. 如果说做出了杰出成就被成为天才, 那么这个天才毫无意义, 拿着放大镜找做出杰出贡献的人是天才的证据才是愚不可及. 你走上了合适的道路, 有着积极良好的心态, 总是比你"低能量状态" 下做事情要轻松一点的. 你有了正确的认知, 日积月累, 你比别人学得要快, 用得更好. 君子善假于物也. 知识方法, 三观和方法论也是物, 也是力量, 也是武器.


你一直忘不了高考, 高考都成了你的一道执念, 但你要知道, 高考是结果, 不是原因. 


搞清基本事实.

不能再这么死板下去了, 灵活一点, 完成任务就是天大的指导. 不要制定什么流程方案了, 来不及了, 也不要死守着哪步要做什么, 只要逮着机会就去做. 只要可以带来一点优势, 只要可以完成就业, 有啥手段都可以使. 完成任务才是目的, 理论不重要, 那是平时看的. 


不要死守条例, 何况你根本就没有什么条例, 想跟着人家学, 你也得手里有货吧? 

再回头已无后路只有一往无前

万念不能乱其心，坚刚不可夺其志

老四，精神点，别丢分，好样的

理论当然重要，但没有实际重要。

一日不找到工作，一日会消耗我的储蓄，一切节省都毫无意义( 这不是让你来找浪费时间的理由的 ), 什么都不做, 反倒日复一日的窝在旅店里面才是最费钱的. 

学习(并使用)和抄袭的界限在哪里？学了不敢用，怕(被说)抄袭？版权。被封锁？自我封锁？知识是特权？到底谁在影响我的观点？是谁将我们压抑成奴隶，丧失生存权，丧失发展权？哪派小说？小说中的哪些观点？
项目和知识混为一体？

你现在最缺的，就是磨练，自己动手解决问题，而不是希望别人手把手教，不是一行一行的抄别人的代码。你解决的问题越多，你越有信心，不是心理崩溃躺平。

先得到原型, 然后再写泛型

找个工作吧, 不要以为浪费父母的钱只是对他们的惩罚,  这也是你对自己的惩罚, 惩罚你的良心, 惩罚你的机会和前途.

读书是为了获取知识, 知识就是力量, 知识可以改变人生, 所以, 读书的根本目的是为了改变人生. 至于所谓的兴趣, 是正反馈的成果, 也就是说, 所谓的兴趣, 其实是力量的副产品. 反而为了兴趣去读书的, 有了兴趣才去读书的, 是本末倒置.有人会反驳, 他就是为了兴趣, 有了兴趣才读读书的, 那是他忘了自己第一次为了其他目的得到了正反馈的经历. 他们在美化自己. 而读什么书呢, 经典自己读不下去, 别的删删减减, 自己有没兴趣, 其实这就是没有自己的思考, 分辨不出对错, 分辨不清好坏的结果, 分不清善恶, 读任何书都会怀疑的, 也就是说没有任何的渠道能提升自己了, 同时也会怀疑自己最开始的时候获取到的常识性的东西, 甚至会怀疑自己第一次接触到的知识, 睁开眼睛看到的第一束光, 这其实有一个根本的规律, 那就是人的一切意识其实都是对现实世界的反应. 只有一个办法, 读书联系实际, 大胆假设, 小心求证.
有时候看到自己不懂的, 比如说, 英语, 或者说一些数学, 然后就完全的隔离了, 想着要一样一样的学会, 学到自己满意的程度, 然后才能来, 否则让自己做一个睁眼瞎, 绝不接触, 绝不理解, 这其实是错误的, 这放弃了一个接触未知的机会, 放弃了一个打破自己位置边界的机会. 而且, 学习的时候不是一科一科来的, 而是对于所有的未知, 我们是 先具体再抽象, 先易后难, 循序渐进. 对相似的领域有过了解, 自己再来学习的时候, 自然是非常容易的, 但这不足以成为自己学习的指导. 


懈怠了啊, 你借到了钱, 然后就想着怎么躺平了, 你需要知道的是, 妹妹和母亲给了你非常大的信任. 信任很珍贵, 不要轻易破坏它. 你的机会很珍贵, 不要浪费它, 失不再来.
我实在不知道你怎么好意思跟人家诉苦, 抱怨, 你自己做的并不好.

你是把自己说的话当放屁了吗?


有很重的厌学情绪, 可以与长时间得不到正反馈有关.

要做自尊自爱，自强自立的人

不论是看小说, 看公众号,  还是折腾Linux, 亦或是看视频, 它们都是一样的, 没有什么区别, 都是一样不做正事, 浪费时间.


基础, 基础, 鬼的基础, 什么都要在基础上面来说, 很多时候是需要做了才知道有没有基础的, 不是靠认知, 而是靠事实.

有的书深奥博大, 但不意味着晦涩难懂, 有的书晦涩难懂, 却是一部垃圾.

善读书, 读好书.


所谓的完美计划，绝对不是等待条件凑齐，至少要尽早准备，宜早不宜迟

没有原则，没有底线，不会忍耐，不会坚持

看小说就不可能准时睡觉，堕落总是一点一点开始，应该毫不妥协，永不妥协

想靠着自己来调节作息已然不可能，必须靠着某种制度，比如上班，但是既然作息自己调节不了，那么时间也不能浪费，必须做点什么，做项目，学mysql,学Linux系统编程

其实你父母对你的付出绝对称得上惨烈

以前一直在想还有多少钱，能过多少日子，却没想过，这些日子干些什么，总是睡大觉，总是调节不好作息

你一直在抱怨条件, 其实这种抱怨之后, 是你不努力, 不奋斗, 自甘堕落. 

我现在这个年龄不去学习新知识，可能以后再也没有机会

学习的时候，不要将你的理解硬塞进去，这不对啊，人家说什么就是什么，你的理解没有证明是对的，也没有被证明能用在这里，反倒是一直被证明在拖学习的后腿

你必须驯服你的灵魂。  控制

五六月最大的成果，居然是调整好了作息

积累不易，要好好珍惜，不要随意抛弃


有一个想法是很容易的, 但要将它实现是很艰难的.

运动, 唯有运动起来一切才有意义. 思维运动起来才不会僵化. 只有在运动中才能学习, 只有在运动中才能进步, 只有在运动中才能发展.
这也许会让你觉得一切都会变慢, 同样的时间你可以做跟更多的事情, 但事实并不是这样. 成就感来源于此, 现实感来源于此, 同时, 这也是你能保证速度和质量的唯一办法, 即专注.  
静止是死亡, 甚至死亡都不是静止的. 静止, 是一切祸乱的根源. 你以为静止下来, 停下来就可以阻止情况的恶化, 但事实上, 恶化得更快了, 情况更加糟糕. 我必须做点什么.
怕这怕那, 其实是怕变化, 有什么好怕的, 不是这样就是那样嘛, 反倒是过于忧虑, 裹足不前才是大忌, 你总要跨过去, 伸头挨一刀, 缩头挨一刀, 那就没有什么可怕的了.  畏畏缩缩成什么事, 想什么话?

你就是太小心了, 不是什么东西都是易碎品, 绝大多数东西都不是, 不用那么小心, 不用活得那么小心翼翼.
不是模仿了所有的细节就行了的, 这不可能, 也没必要, 重点是抓住主要的矛盾, 抓住关键, 抓住重点. 不要再拙劣的模仿了. 胆子放大一点, 不要有那么多顾虑, 不要怕. 没有什么的. 做一些流畅的动作, 不要滞涩, 不要怕, 顺畅一点.

照着抄肯定是不能抄了, 只要求
                      1) API 相同
                      2) 相似的测试能通过
                      3) 代码应该简洁直观, 不能像人家写的那样, 不能照着抄了, 太多了, 太复杂了
                      没必要
                      1) 做很多额外的工作, 比如iterator.h

7月6日的debug其实是做得不好的, 首先, 当你知道自己的代码错误的时候, 就应该排除其他的干扰, 比如, 其他的测试大大浪费了编译和运行的时间, 那么这个时候就应该用注释代码或者删除代码的手段来节约时间, 缩小范围. 其次, 你既然可以有一份完全正确的代码来做对照, 那么就应该用好它, 不用自己费心费力的思考逻辑, 思考代码具体的运行, 不一样的地方肯定是错误的地方, 灵活一点, 不要那么死板, 不要一直想着蛮干, 横冲直撞解决不了问题. 然后, 你用了gdb, core等工具来定位问题, 用了插入信息的手段来定位位置, 这不算错, 但还是很稚嫩, 运行了很多次都没有意识到问题在哪里, 这里有两个原因, 一个是经验不足,  一个是代码不是自己写的, 不太理解, 也就没有那么敏感, 不知道其中的逻辑.

一个是不专心, 一个是没经验. 前者, 不要在写代码, debug的时候看视频, 看小说, 不要打断思路, 不要被分散注意力, 一心二用是大忌. 后者, 需要写代码, 不是抄代码, 自己写一些代码, 自己解决其中出现的问题. 多了之后自然就会快起来.

不要在情绪激昂的时候, 在能快速解决问题的时候 去享乐, 这是对你自己成果的不负责, 不要半路开香槟.

写代码的时候不认真, 调试的时候真的是火葬场啊.
                       
一卡就是两个月, 时间线拉得太长了, 不能再这样了, 怎么办?

项目有了困难, 不在项目上解决, 反倒求起了所谓的思想, 心态, 这算不算是一种不问苍生问鬼神? 算!

看了那么多小说，唯一的一点好处就是宏大的叙事让我开阔眼界, 知天有多高, 人定胜天.

防止思维无休止的扩散，特别是学习的时候，可能会对其他知识造成污染. 扭曲认知.

太有用，太好用，为何不用？在不知情的情况下, 即便下方是万丈深渊, 也只有一脚踏进去，这就是无知—没有认知或认知不足的风险，但不能因此自己认为可以的也畏畏缩缩，不敢去做，那就什么都都做不了了。

内心缺乏动力和自我价值感.

必须要能控制自己的思想。

性格需坚韧，学习需勤奋，既然都没有，那不如干这个.既然其他的也不怎么好的话, 那就选这个.

debug, 需要从第一个不对劲的地方开始. 不能哪里崩溃了, 然后就去找哪里, 这就是所谓的头痛医头, 脚痛医脚

你嫌弃父母唠叨, 你是嫌父母影响你的进度还是嫌弃父母打扰你闲着的生活, 你有没有想过? 以前可以说是扰乱你的进度和心态, 但是, 已经这么长的时间了, 父母也没有时时出现在你的眼前, 你很闲, 你又看了什么事情呢?

要去做, 要去体会, 只坐着想, 是想不出来也理解不了的.

要学会接受别人的意见. 避免错误, 前进, 都是少不了接受别人的意见的.

我真的不知道我还要骗多久. 

前怕狼后怕虎, 畏畏缩缩的, 怎么成事啊.

你是就将晚上12点看小说当成你一天的目标吗?

问题知道了, 那就要解决啊. 不然知道了又有什么用呢? 不要说无力改变的话, 这并不是什么困难的事情, 事实上, 这可能是很简单的事情.


既然没有喜欢的, 那和不选择一个来开始呢? 你已经选择了, 不是么? 就算不喜欢, 没有兴趣, 又如何? 难道就做不好了? 所谓的喜欢, 不过是长时间的不间断的正反馈罢了. 所以培养喜欢, 不过是要达到的学习的正反馈和实践的正反馈, 为了达到此目标, 那么就需要理性的按照自然的规律来完成, 而不是按照喜好来完成, 特别是不能按照自己随意的意志来完成.  喜欢不是天生就有的东西, 兴趣也不是天生就有的东西.所以, 按照自然规律来办事情, 其实也就是取悦自己. 你看了太多垃圾小说, 无病呻吟, 得过且过, 沮丧悲伤, 没有一点出息, 像是被打断了脊梁骨, 遇到了一点困难就呻吟放弃, 喝酒泡吧有之, 乱交乱搞者有之, 像是个畜生. 这是藏在你思想里面的毒, 需要注意, 需要拔除.

一直做不到，不止有精神的原因，身体精力也是严重不足的

改造，要进行思想改造，不然就完了

人在落难时，往往能看出一个人的底色。你看看你，现在有一个朋友帮你吗？你以前是没朋友吗？他们人喔？

别被吓得不敢往前走

"一方面是功能确实够用，界面看着也熟悉，反而思维比较放松，人进入一个比较熟悉的环境，就会容易进入一个”专注“的状态"

学习，必然有一个熟悉的过程，也就是一个思维负担的过程，然后才会轻松起来，使用的时候才会得心应手。反倒是你以前的想法，为了适应所有，都不学，反倒是退步的过程，反倒是为了躲避努力的懒人行为。事实上，不可能适应所有，也没必要，况且你也不可能接触所有，所以确实是应该好好学习某些知识，某些操作，这样才能提高效率。很多东西，记得就好，而不用记得它是推理来的还是发现的

虽然数学被某些人吹得神乎其神，好像数学是万能的, 学了数学其他科目特有的东西也学会了, 但这是不可能的, 还是很有必要接触社会, 学习相关的社会知识的.

大病，病去如抽丝，我现在就是这样, 不可能一蹴而就了, 病已入骨, 非得长时间的改变不可.

无所作为，不止节省, 得过且过，懒惰成性，惯会找理由拖事情，要改变，学着去做你不喜欢的事情，试着去做让你感觉不舒服的事情，，有了结果之后，你一定会发现对的事情一定是会让你更喜欢，更舒服的，怎么可能做什么事情都是舒服的呢，长征最开始的一公里是最难走的，走下去就能活过来

我没有机会回去了，欠了很多钱，回去没有收入，还不上。

听人劝，吃饱饭, 多听听他人善意的提醒, 生活真的可以变的顺利不少,  听得进别人的意见，能接受别人的批评，而不是只自我批评，光自我批评有什么用。也不要总是想着别人的所谓基础逻辑是什么，借口罢了，对不对，其实你心知肚明，现实中也可以看得出来，现实是总的阅卷师，

不要有防御性的姿态来学习编程, 来找工作.

不能闲着, 思想要一直在运行, 总要想点什么, 不然就停摆了, 想点问题, 回忆一下知识点, 也是好事情嘛.
林彪, 粟裕背地图, 用得时候想得起来, 速度也快, 熟悉, 做一些决策时也会很肯定, 不至于想问题的时候还看地图, 有一些东西是要背的, 需要背熟悉的, 不能只是理解理解, 这是不够的. 父亲的话, 当个参考, 他有的话是很片面的, 不能全信, 不能照搬.

不能随随便便, 什么都不在意, 认真点啊, 拿出点态度和力量来. 来点真的.

不能再这样稀里糊涂的下去了.

有的事情很好笑, 也很有趣, 自己却不能真的去做, 不要把自己活成别人的谈资.

不能光说不练啊. 不然学不会.  敲代码, 直接上手做练习.

睡眠问题是大问题，但不是决定性问题，不是关键问题，问题是心理上的. 但哪怕睡眠问题不是最大的问题, 也应该注意精神的修养. 哪怕不是关键，也要解决，不难的，很容易，为真正的问题继续能量
既然能够解决, 那就不能让它摆着.

现在距离过去已经一年了, 应该再好好想想了.

学点新知识吧.

逼一逼自己.

一有钱就丧失理智了，没有动力，没有上进心了，完全躺平，只会吃，只会玩，怎么能这样。
花钱不能大手大脚的啊, 节约着点.

一直想速胜, 这不可能, 一个多月前就知道, 但还是一头冲进去了.

不要将编程当成写一篇文章, 那实在太无趣了, 太令人厌恶了, 应该当成一个问题的解题步骤

世界上只有两种人生态度，一种是奋斗的，不屈的，另一种是躺平，得过且过的，浪费人生的。关键的问题就在这里，如果人生态度的问题没有解决好，再多时间都没用。

你明明知道该做什么，却犹犹豫豫不敢去做，怕付出代价，却总是因小失大。其胜也常，败也常，为什么不去试试呢？


早点就业就是省钱.



绝望是吞噬心灵的毒药，生活应该积极开朗

你以为是父母逼着你走，不，不是，是现实逼着你走，在学校里没有积蓄够足够力量去工作的你，只能这样被逼着走一步看一步，反倒是他们一直在支持着你

上学时一直拖延，积压的学习债让我对现状无能无力，积压的睡眠债让我没有精力活力，积累的坏习惯让我几天积累的精力总是清空

社会的, 国家的福利你真的没有拿到过吗? 举办的一些赛事, 活动, 你为什么不参加? 全国举行的高考你认真对待了吗? 老师是让你学习知识的, 你读书17年, 你问过多少问题呢? 你请教过些什么? 考公考研事业单位编你认真对待了吗? 不是没有, 是你不屑一顾, 是你各种看不起, 是你忽视, 就好像什么都不要靠着所谓的自己就可以做一切事情一样, 这是错误且恶意的引导, 世界上没有做成这种事情的人物, 没有所谓的这种英雄. 你应该充分的利用一切你所能拥有的一切资源, 这才是正确的态度, 你应该保持充分的足够的理性. 你自己所弄的那一套所谓的知识体系, 思维体系, 学习体系, 在哪呢, 最后有什么效果呢? 不过是浪费了宝贵的十年时间, 什么都没有得到. 你死于你的傲慢. 福利不是扶贫, 需要你上前走两步, 伸出手够一够, 不是人家把饭舀起来喂你嘴里, 是需要你自己努努力的. 

我不知道什么是喜欢, 它来, 它有, 我就去做了. 所谓喜欢, 不过是不断的正反馈罢了.

不能懒散随意, 我没有资格这样做, 也不应该是这种人. 这很痛苦. 


没有什么一辈子的工作. 你必须时时刻刻改变自己以迎接挑战.

世上没有什么躺平让你干一辈子的工作, 你必须持续不断的奋斗.

不要被easy girl和外国垃圾男影响了，你出去看看，凡到外国站起来的中国男人谁不让外国人闻风丧胆，自信点，国男

再难也得做啊, 不做就天天这个样, 没个头.

我不知道做什么，所以我不管做什么都有一种可惜浪费的感觉。我不知道什么是有意义的，所以我怕做这事的时候我老了，但还有其它更重要的事情没做

精力太分散了，一会要这个一会又要那个的，做着这个又想着那个


* 项目困境
我先去做，把项目完成，什么样我不在乎，做完就行。
既然决定做STL，就不可能不和别人的一样，希望面试官问我的时候我能让他满意吧

有点目标, 有点要求嘛
我需要做什么, 答: 做一个STL的微型项目. 我不知道很多东西, 但我需要参考, 我需要做点不同的, 如果是我来做, 那么我会怎么做呢? 这就是区别, 这就不再是抄袭, 


既然要改的不一样, 那么就不能看好不好了, 只要能运行, 就可以


你这事吧, 其实说到底, 就是优秀的人比你太多了, 把自己搞抑郁了, 但是呢, 又不敢承认别人比你优秀, 所以呢, 就装疯卖傻的骗人, 骗父母, 骗老师, 自己一个人躲起来,  但什么都没有干, 这造成了一个什么结果呢, 就是差距越来越大, 恶性循环, 最终导致了一个这么结果, 原因真的不复杂, 解决方法也不复杂, 不是什么建立自己的知识体系, 不是什么学哲学, 也不是什么学习高等数学, 那是以后学的, 更不是钻牛角尖一个公式看出花来. 那就是接受别人比自己优秀, 然后踏踏实实的努力, 好好听老师讲课, 好好做作业, 不怕觉得这件事情丢脸. 当初不就是感觉丢脸才不敢跟父母说么, 问题就出在这了, 什么都不说, 人家不知道, 你自己也怕人家知道, 所以呢, 就各种掩饰, 上面那些就是掩饰, 搞到最后自己都不明白了, 迷失了, 就像搞一个游戏,防盗版的工作比游戏本身还要非精力, 这不就注定得死嘛.
倒也不只是丢人, 想想以前的样子, 看看现在的样子, 只敢躲着走, 时间长了呢, 就害怕接触外界社会了.
当初有多么自大, 现在就有多么自卑.

原来你是对的, 你们是对的, 只怪当时太年轻, 太无知, 以为一切常识, 正因为太简单, 所以以为到处都是, 真想回到过去, 再受你们的教诲, 可惜, 回不去了. 国家对我们的教育是对的, 真正遵循, 不知道能少费多少功夫, 少走多少弯路, 可以避免多少深渊般的陷阱, 可以防护多少伪善的诱惑.

也不知道从什么时候开始, 我变得好吃懒做, 鬼迷日眼的, 不过应该不是从高考失败开始, 在高考失败之前, 我的生活习惯其实就很差了,  不过那个时候不在意, 没有丝毫的警惕之心. 也不再学习了, 自己装作在学习,骗过了自己, 害了自己.

不论是B站的视频, 还是小说, 其实都是麻醉剂, 麻醉我的精神

我害怕了, 我害怕不够格, 也不敢去投简历

不能人到三十也没有长大啊.

我做到了极致, 所以也输得彻底.

这个条件之下，一鸣惊人是不可能的

要不是父母催促你，你早躺平躺废了

学习，要先看一遍，然后来做，不能边看边做，我非常不适合这种方法。

还是要有点压力，但不能寄希望于一蹴而就，不能希望一天甚至就解决问题，不能希望一次就解决所有问题，哪怕是关键问题也不行，问题解决总是这样的，今天解决几个小问题，过了几天一个大问题解决了，过了半个月一个月或者几个月大部分问题解决了，过了几年十几年发现达到目标了，这样才对，特别是对于我的期望我的梦想来说

一次不要想太多, 也不要一次想太多问题, 容易抓不住关键, 除非那么有不容忽视的联系.

做一件事情是需要时间的, 不能一次就做太多事情, 量力而行.

只有认知改善了, 才能祛除掉这么多年留下的后遗症, 但认知不是孤立的, 必须参与社会生产, 参与社会实践才可能产生, 它与现实社会密切相关, 它不是飘在空中的楼阁, 不是思想里面自然产生的, 必须通过既有认知和现实的残酷斗争才能产生, 而这个过程中, 为了避免陷入迷茫, 为了不偏离真理产生片面的认知, 那么我们就必须, 然后实践, 然后再学习, 再实践, 循环往复.

信息来源于网络, 三观来源于小说, 这怎么可能变好呢?

很多细微却不易察觉的差别, 需要你学习并理解了很多知识才能懂的. 当然, 不乏很多了解了几个知识点就能弄明白的差别

熬夜, 这个习惯, 已经严重伤害我的身体健康了, 必须改正.

权谋的本质就是做事的方法，要有事才有权谋

像性张力这样的概念，非得写写哪些人有这个东西，其实说明这东西既没有内涵也没有外延，是个伪概念，估计是哪些人遇到或者发现了这东西，但又不知道是什么，又不好学也不探究，起了个名字糊弄人，也不管以前研究过这东西人给它起的名字。

感性, 其实是动物性(?) , 人也像大象那样, 知道疼, 会讨厌痛恨让它疼的人, 但是人的理智会告诉他自己什么疼是对自己好的--比如打针, 什么是不好的, 能压制本能的冲动.

不讲真话, 以后连你自己页不知道真假了.

学习不能只看, 还有动脑, 用心

elisp 还是需要学啊, 不然要定制点什么无能为力

不要想着走捷径赚钱, 不可能的, 必然付出惨重的代价. 不要想着赚快钱.

两年了, 你应该惭愧, 你什么都没有做, 找工作什么都没有找到, 成天不是看视频就是看小说, 遇到点困难就退缩了. 你辜负了父母和妹妹的信任.

既然学又学不进去, 遇到困难又解决不了, 那就找个工作吧.

你要理解父母的苦心啊, 这么久找不到工作, 谁都急啊, 自己不争气, 被说两句也是应该的.

你害怕接触社会, 其实就是害怕接触人, 你不知道怎么和人建立关系, 并维护这种关系, 即使建立也会逃跑.


同质化, 怎么办?
删改
重命名
调整程序结构

这个改, 便是要简化, 不能这么完善, 不能写这么多.


SUM 是错的, 必须要有坚强的意志, 不是顺着就可以学会的, 总是会遇到很多困难, 不是一句SUM就可以的, 根本上就错了. 理性强于本能. 

快乐教育是谎言, 是骗局.

思考, 就是将别人的思想提纯为自己的思想的过程. 也是吸收学到的知识的过程.

我发现, 只要我不要求自己做一个某种意义上(我尚不清楚)的好人或者说老实人, 那么真是天地宽广啊.

突破信息茧房，不能整天看段子不干活

编写程序

过去记挂着的事情有时间做就去做了，不要老是记挂着.
记挂着新的东西又没法学，静不下来学，新事物又老是不能接受，任务也完不成

不能偷懒，必须的事情必须按时做掉


3月9号, 我的劫难日, 不止是在这一天我受到了欺骗, 遭受了经济损失, 更重要的是, 我从那天开始, 从微信借钱, 开始不把钱当钱了.

因为我觉得我可以速胜，所以一直拖，拖了四个月，欠了很多钱，花了一万多块，毫无意义. 一直拖, 所谓的项目, 其实也没有多大的体量, 但就是浪费了我四个月的时间, 几乎所有的时间都放在上面了, 一无所获. 可惜了, 如果我在3月能继续学下去, 保持住状态, 也不会这么被动.

你就是完全不清醒，自己要做什么，该做什么，自己完全不知道


自己独立一个人开发项目是不行的, 大多时候都不会是去开发, 有一个人带这比较好.

思想和意识这种东西不能乱改, 就算要改, 你也要知道怎么改回去, 不然非常非常麻烦.最好做个备忘录, 初衷是什么, 目标是什么, 步骤是什么, 意识里面想什么, 如果可以还需要分析一下潜意识, 记录一下当前状态, 分析当前困境. 否则很容易迷路, 陷入迷茫和狂乱.

在一切透明的前提下, 只有阳谋才能战胜阳谋, 阴谋永不持久, 也就是说, 只有运用真理才能战胜真理, 只有运用真理才能战胜一切阴谋诡计. 毛主席太过于厉害, 太过于牛逼了.

战争是最残酷的选拔人才, 选拔最适应环境的人的方式, 没有并列的第二种.

你买电脑来就是为了看视频的吗? 编程啊编程, 数据库啊数据库, 这才是买电脑来的目的.

坐吃山空啊.

找到问题把它改掉, 如果还是不行那就继续找问题, 直到解决, 处境不是一个问题造成的, 肯定是很多问题造成的, 所以,一直找一直改.

策略失误啊, 我以为STL可以几天就完成, 当成一个锦上添花的项目, 但没有想到, STL居然也浪费了我这么多的时间. STL不能速胜, 拖慢了我的脚步, 打乱了我所有的安排. 是我小瞧了STL了, 去年STL就是抄的, 没有理解透, 而且当时STL做的也不全(我以为已经很全了, 只要改一下就好), 一个判断失误, 造成了很严重的后果. 如果早知道是这样, 如果早点知道这种情况, 换一个项目也比这个好啊, 可惜我还对速胜抱有希望, 错得太离谱了.

不要老是掉在男男女女, 情情爱爱的陷阱里出不来了, 没有的, 要是没有点本事在身上, 怎么谄媚都没用的. 你被他们骗了, 想用感情来得到她们是不可能的.

做什么都想几天干完, 没有什么耐心, 不会坚持去做, 几天没做完就不想做了, 来来回回反倒是比一天天坚持做, 每天都要做点什么出来, 直到做完更浪费时间, 浪费精力, 浪费金钱.
网上做宣传的只要是做宣传的, 都不要信, 没有什么水平, 做学术也没有水平.

我发现我其实我一直活在某些破坏国家的组织的思想阴影下, 比如, 谨小慎微的处理人际关系, 害怕其实没有什么威胁的小错误, 等等, 我得好好想想, 再找出些实例来, 然后改正, 我怀疑某些小说作者在自己都不知道的情况下被影响了, 我同时也怀疑某些写出一些所谓"黑暗现实"的东西的作者, 其实用心没有那么单纯. 换句话就是魔怔人, 比如一句女性不好的话都不能说, 看看美国, 看看美国, 例子多得是. 一些小说里面描写的封闭环境下的洗脑如何应对? 没有隐私的世界是可怕的, 你什么都会被人知道. 另一个原因就是网上对社会, 对世界黑暗的描绘(当然, 还有小说的影射, 也许这不是国家监管的要求, 但企业却这样做了), 也极大的影响了我的心智. 必须承认, 有很多的社会荒唐黑暗的事实被影射到了文艺作品中, 但不应该产生这么大的威力. 我活了二十多年, 遇到过不好的事情, 但不是每天都这样.


我就不信就找不到一个工作.

人们对一次性支付代价总是慎重, 但又对持续性的放血视而不见.

不能再捂着耳朵干活了, 做出令人不耻的决定和行为了.


理论可信, 人不可信. 但没人又怎么有理论呢? 不信人, 又怎么相信理论是正确呢? 不信人, 理论就是空中楼阁, 看理论就是雾里看花.

1234是用来整理的, 是笔记时候总结归纳时候用的, 不是在学习, 记笔记的时候用的, 这容易限制思维, 打断思路.

我终于知道为什么我要一点点的检查, 需要没有抄袭的嫌疑了, 在这个追根究底的时代, 任何一点瑕疵都可能导致失去舆论支持, 任何一点错误都可能导致失败, 没有人能经得起被人拿着放大镜查.

作息成了最大的问题, 作息完全混乱, 日夜颠倒, 必须强制纠正, 不允许再睡午觉, 不要再手淫, 每天按时睡觉. 哪怕死撑, 也要撑到作息正常. 在这期间, 哪怕在痛苦, 也要学习mysql, C++, 网络, 也要写代码. 最早晚上10点钟睡觉, 最迟3点, 应该逐渐调节.

关键时候没用, 那么什么时候都没用了.

不要抽离出来, 去体会, 去沉浸.

对父亲说话语气好一点. 今天逼迫父亲, 我几乎撕破脸皮, 他回避了, 但感觉他好像不是怜惜钱财, 这是怎么回事? 他好像想控制我短人生过程, 1. 工作 2. 结婚. 不算错, 但我不喜欢, 需要自己去争取话语权, 经济收入就是话语权.

成年了, 每句话都会受到别人的认真对待, 责任更大了, 每句话都得有的放矢.

一切都是工具, 知识, 资料, 耗材, 都是为了做事情, 做事情才是最重要的, 也就是说, 对于知识来说, 应用才是最重要的.你不能掌握十全十美的知识, 也同时就是说, 你不能十全十美的掌控知识, 不存在完全的掌控.

不要对死气沉沉的东西感兴趣.

做点有趣的东西.

真心最怕辜负

在学习上，被动的习惯和适应是错误的 

做学问不能有侥幸之心，学习也是

我的问题根本不是什么哲学问题, 那只是表象.

盖明者远见于未萌，而知者得避危于无形，祸固多藏于隐微，而发于人之所忽者也。

早没了雄心, 又怎么做得成事情呢? 早知如此, 我不应该妥协的.

帮我弄清楚是什么, 为什么的, 就是资料, 资料的载体包括但不限于文字, 图画, 视频, 声音.


世界观, 人生观是到了差不多岁数就会形成的, 不是你想不形成就不形成的, 只是明显的不明显.

你总是放弃啊.

作息调节得不错, 现在要戒烟, 戒酒, 戒淫, 不看小视频.

自古以来, 无知才会无畏, 你懂了, 也就没有那么畏惧了. 所以, 勇者总是有认知, 有知识的人.

疏不间亲

自己的事情不能什么都让别人知道, 事以密成，语以泄败

需要守规矩, 你所谓的自由后面全是混乱.

戒烟, 戒酒, 戒色, 不要看娱乐视频.

规矩树立之后就必须遵守, 不容破坏, 一旦破坏, 就不是现在的这个规则可以束缚的了.

学会克制自己的欲望. 

写程序本身并不是目的, 配置编辑器, 配置terminal, 配置tmux 都是为了更好的, 更舒服, 更方便, 更快速, 更快捷地编辑代码.
程序本身不是目的, 编写代码, 编译程序, 是为了用这个程序干什么这才是重要的.
代码, 程序本身是为了人服务的, 是为了达成什么目的.
凡事都有目的, 更重要的事情是不能将目的和手段搞反了. 我们用typera编辑文本是为了得到一份漂亮的文件, 我们用软件写小说是为了写小说(不管是为了什么而写)而不是为了用这个软件, 不论是libreoffice, 亦或是其他的都可以(也许GNU就是搞反了这个东西才不能壮大, GNU的软件需要首先需要回答能做什么, 然后才能回答GNU本身的目的, 如果仅仅是一个替代, 那么结果可能不会太好.). 我们使用emacs编辑代码是为了写一个程序, 这个程序能让我们干什么, 而不是为了单纯的用emacs. 
所以什么优美简洁的代码都是目的的附属品, 而不能当成目的本身, 是在达到目的的这个过程中产生的. 如果硬要追求这个, 那么会陷入虚假的美的陷阱中间. 数学其实也是这样. 它们具有美的特性, 但是它们绝对不是美, 美只是一个特性, 是一个附加的属性.
所以单纯的为了做什么大概率是不能持久的, 总是需要有一个明确的目的. 这意味着在那一刻是需要确切的状态的, 不能既想这样, 又想那样, 似乎什么都是, 又似乎什么都不是, 这是不可能的, 也是不对的想法.

没有目的不用动身, 没有需要不用超前做什么准备, 你可能在做无用工.

你学了什么样的知识, 有了什么样的信仰, 就会成为什么样的人, 这是可以肯定的. 你可以伪装遮掩, 但无法消除抹去. 这是你的印记.


事实上, 只有一次掌握知识的机会, 如果第一次没能彻底的思考学习清楚, 那么下一次见到的时候, 我就会将它当成掌握的知识, 轻视它, 最终错过. 每一次的复习, 其实就是回忆第一次的映像.

以后记录灵感和想法, 以完成为主, 准确性后面改动来保证.

我看小说的时候, 会屏蔽某些东西, 这是一个大量阅读网络小说的习惯, 为了不被其影响筑起的防御, 只有将它们放出来, 我才能更好的学习, 这是一个猜想.


我是否有一件很重要的事情没有做, 所以才这样害怕?

完全没有想过, 完全没有计划, 要干什么, 怎么干? 有点进展就摊那里了.

什么是会的, 是什么是不会的, 这是一个重要的问题, 搞清楚这个问题才知道自己是什么实力, 才能有的放矢. 什么看过, 什么没看过, 什么看过还需要在看看的, 这是很重要的问题. 这样才能查漏补缺.

阅读文献 书籍
编写程序
书写知识 真理


人哪, 不要想着走捷径, 不要想着躺着衣来伸手, 饭来张口, 人家天才之所以是天才是因为人家走的是正确的路, 人家也是老老实实走的. 要真的走到正道上, 不知道会避免多少直接的和衍生的麻烦.

我看了太多小说, 对我的负面影响, 对我的扭曲影响实在太大了.

为什么我不敢要一些机会? 因为我知道我是有问题的, 我真的害怕伤害他们.

自己的东西不要随便给别人, 别人的东西不要随便要.

我们不可能做所有的事情, 人力有时穷.

不寻求大的, 剧烈的改变, 这种事情这能润物细无声的去做, 慢慢的改变, 或许几个月或许几年.

为了母亲，做出点事情来，不要让她受辱，她在我幼时顶着父亲的家长威严维护着我，我又多次伤了她的心，现在更是她支持着我，我不能让她被人看笑话，以为她教子无用无能

雄心被消磨了，雄心不是能思考出来的

云峥拍拍苏洵的手道：“错的离谱了，现在所有的辽人都知道自己还有这么大的一个宝藏未动，所以他们就不会有紧迫感，都以为自己还有退路，却不知这种退路恰恰就是让他们逐渐衰败的原因。

有了退路，在重要关头他们抵抗的决心就不会坚决，我们胜利的可能性就大，等到分配宝藏的时候，他们必定会起内讧，辽国人的日子一定会雪上加霜，有这笔钱，还不如没有，贪婪和侥幸这两种心思组成的麻烦，根本就是一个无解的麻团。”

萧打虎没有在第一时间率军突围，已经让云峥小看了他三分，粮食不足是他最大的弱点，继续缩在西京城只会让他的力量越发的衰弱。


最大的哲学是死亡，如果没有矛盾，没有对抗，没有斗争，那么一切都将死气沉沉，一切文艺作品都没有意义。

你需要用所有力量来解决，不能在封闭封印下去了，不能再封闭五识五感了

生命可贵，丰收可喜


我丧失了信念，丢弃了理想

还是对考试测验心怀畏惧，甚至是恐惧，我不是害怕有不会做的，我是害怕全都不会做，太多次相似的经历，刻画在我的血脉里，让我恐惧，模拟考，高考，考试，考研，考公，都是，太让我害怕了，我知道我可以不止这点水平，但是，怎么就到结束的时候了呢，我还没来得及。来不及是最大的遗憾。没有受过系统的教育，只是看了一点视频，两本书，怎么学得会，而且还都没有读得懂。

你经受过考验，可惜你没经受过考验

以前想走捷径，却又不坚定，心里还想着别的，想走不敢走，最后落得这么个下场，还付出那么多代价，真是让人唏嘘。一步一个脚印，比什么都强，不走弯路就是捷径。

自我精神分析


保护性学习，保护性记忆，一层防护，没有直接到大脑

什么是资源，资源是拥有的，可用的的东西，这个可用，指的是全体人类，而不特指拥有者


有能力才可以做事情，做事情可以锻炼能力，但做事情才是最重要的，不能主次不分，能力固然重要，但不是天生的，是一次次学习，实践得来的，实践是人一切的源泉，先实践才有能力，有了能力却无事可做，才是悲哀，如果只强调能力，不强调实践，那么空无依托，不论从精神上还是物质上，都会迷茫空虚

对我伤害很大，潜意识忘记并远离，是自我保护机制起作用

有什么样的知识并不意味着有什么样的三观，在于行为和思想，也就是所作所为，所思所想，所以，人到了一定的年纪必定形成属于他们的三观

我的准备并不充足，这也是我不做的原因之一

心胸太狭隘了，太死板了

品性不太好啊

不上赌桌, 不上贼船.


丢掉几层多余的面具，好好活着

想要全力学习，必须解决学习抗拒的问题，之后无论是逼迫还是兴趣诱导，都可行

是啊，总好过什么都没有做，世界上最悲哀的不是失败，而是什么都没有做，什么都来不及做

科学，可不是躲着在房间里摆弄的玩具，而是整个世界

马哲上的矛盾指的是力量，而不是逻辑矛盾或者逻辑问题

适应消化放松的状态，持有它，掌握它

该走的路总是要走的, 逃不掉.

不能害怕浪费笔墨, 不能害怕浪费纸张, 不能害怕浪费书写空间, 将精力浪费在这种小事身上, 干不了大事情的.

学编程那就不能怕麻烦, 不能怕找错误, 不能怕学习.

开放的心胸接受知识, 接受世界, 你可以的. 别总想着建你的知识大厦, 整个知识体系, 八字还没一撇呢.

可能在人家看来, 不反对就是支持吧. 做好你自己的事情! 不要总是抱怨别人如何如何. 少看些原生家庭不幸的视频文章, 幸运也会以为自己不幸

理解, 而不只是熟悉, 想靠着多看几遍熟悉之后再理解是不可能的. 要付出的努力, 要经过的艰辛, 一个也不会少. 不如直接的, 不经过弯路的要理解要好. 并不能加速, 反而倒是犯了不认真的错误. 所以不能以为看看答案, 记住思路, 知道怎么解题的, 看看代码, 知道人家怎么写的, 那里优秀, 有那里需要改进就以为完成了, 最重要的一步--其实也应该是第一步是, 自己思考, 然后写出代码, 测试, 找出问题, 最后才来看答案, 光看答案, 不但不能节省时间, 反而是浪费了时间, 因为你根本就没有什么印象.

想着躺平然后找到工作, 这简直是世界上最好笑的笑话. 这不是随随便便就能达到的目的. 一切收获都需要付出.

蛇吞象, 不能停, 停了就死, 只能抢时间, 全力消化.

为什么这么慢? 战术上的便捷快速, 弥补不了战略上的缓慢愚钝, 换句话说, 不管你使用的是什么软件, emacs也好, alacritty也罢, 不管你用的是什么工具链, 不管你打字速度多么快, 只要你策略和执行策略的过程中是拖沓和笨拙的, 那么永远都不能真正发挥你所使用的工具的真正作用.

战术上的快捷不能取代战略上的懒惰, 不能弥补战略上的懒惰.
路径错了, 再快也不能快速到达目的地
方向错了, 再快也不能得到准确答案.

事物, 它有准确的度, 未必有准确的时间(质变),准确的说没有准确的质变时间, 想要精确的几份几秒甚至几毫秒是不可能的, 也是没有意义的. 只知道有一个准确的度(这可能意味有一个飞跃的剧变的事件发生), 我们将这件事情发生的时间成为剧变的时间.

不要害怕被人揭穿, 而是要不断的扩展自己, 不断的增强自己, 要靠自己的本事征服别人, 不要让人意味自己什么工作都没有做过放低要求, 不靠别人的怜悯工作. 不要让别人将自己当成一个刚毕业的毕业生, 自己也伪装成这样博取同情. 你过不了关的.

记住事实, 再来谈观点
一切的辩论都是围绕着事实的辩论. 一切的思考, 都是围绕着事实的思考.

若无与苍天争雄的勇气, 怎么可能学好C++呢?

不用刻意的将自己装饰成一个刚毕业的大学生的水平, 毕业两年了, 不一样了. 只要自己学会的, 就用上去. 不然人家认为你不合格.
不要害怕人家认为你在抄袭, 超出自己的水平太多. 只要自己会, 那就弄上去.
不要再装刚毕业的大学生了, 项目嘛, 有多少力用多少力, 力气不够网络来凑, 缺少什么找AI看

改造我们的学习, 我现在需要改变的是理论学习的方面, 实践方面不是不重要, 但是如果理论学习都学不好, 那么实践也是搞不好的.
理论学习, 最怕的就是曲解, 误解.
但我们无法脱离实践, 我们时时刻刻都在社会实践, 我们实践却又缺乏理论支持的时候, 我们应该学会记录和总结, 这对学习理论也是大有好处的, 不能没有掌握理论就将实践抛弃, 这是得不偿失的. 就算我们没有完全掌握理论, 我们也应该和理论对照, 对比错误, 这样对理论学习也是大有好处的.

不够果断啊, 其实没有什么好选择的时候, 只能选择走下去

不能丧失斗志啊, 不能放弃奋斗啊, 经常感受到难以承受的压力, 然后就放松了, 躺平了, 这事不对的.

其实只要走下去, 就成了自己的路了, 太刻意了, 反倒不美, 反而让自己刻意的躲避了正确的路途, 每个人的路都是不同的, 走下去就不同了.

还是需要先看清楚才来做, 不然太盲目了, 浪费时间, 不能一直用尝试来作为得到结果的手段, 必须要一些必要的知识. 还是先看看人家怎么做的吧.

一直是这样, 情况有点好转就不管不顾的去玩了, 三天打鱼两天晒网是要不得的.

先弄清楚结构(比如list是环状双向链表), 然后再弄清楚基本的调用, 然后就可以按照接口要求来写了.

有的路注定是错的, 不要那么固执, 错了就回头啰. 回头是岸, 不要听人家说什么有的路注定是错的也要走下去, 你不知道人家被现实毒打得多惨, 有的人只是嘴上说说而已.
一条路只要它本身是正确的, 那么不论外部打击有多大, 但它的生机是掩盖不住的. 这是可以直接的, 深刻的感受出来的.

一天天的, 也不学点好的, 整天抑郁, 开朗一点.
不要在情绪上压制自己, 已经够了, 足够了, 再压制也没有用了.


写程序要按照调用关系来写, 这样才不会搞昏头.
写程序, 要以一个为主体, 不要一会看看这个的, 一会看看那个的, 三心二意做不成事情.
找问题, 调试的时候也是这样的, 从调用关系入手, 而不是从基础的被调用的接口(一般是函数)入手

一心二用, 一心多用, 这种事情要少做, 做了还做成功的, 在一生中屈指可数.

调试器的妙用: 写完代码, 然后用gdb运行一遍, 看看程序是否像你想象的那样工作.

做事情千万不能三心二意, 必须专心致志, 一心一意. 容不得半点马虎. 东打一榔头, 西打一棒子是不行的. 写程序, debug也是这样

写也写了这么多了, 时间也过去这么久了, 进度推的这么慢, 其实就是不熟. 对什么都不熟悉, 所以才走得这么慢, 这么磕磕绊绊

他们不给我机会, 也怪我自己不争气. 也就只能这样了.

但如果没有了这种唠叨, 你会不会后悔? 2024.10.06: 会

眼高手低啊

2024.10.06: 终究是和父母都决裂了啊, 我并不埋怨被放弃, 是谁七八个月什么事情都没干好, 一无所获, 都会想放弃的. 我埋怨你们为什么逼得那么紧? 但你们能不能别逼得那么紧啊, 三天一小问, 五天一大问, 这谁受得了, 我想找一个像样的工作, 不可以吗? 有那么难吗? 我的要求并不高啊七八千块钱一个月, 要求很高吗? 给我点信任, 给我点时间, 我可以的, 你们的精神支持真的比物质支持重要. 你们让我考过公, 我知道真正的支持是什么样子的. 你们以为离开家就万事大吉, 怎么会有这种想法? 我离开了, 但人家的要求会变吗? 不会啊. 你说让我去培训, 我告诉过你, 培训真的不重要, 我可以学的, 然后就是无休止的问, 你既然认为我应该去培训, 认为我不行, 还是说你认为我什么自我认知都没有, 我不去我自己就是行, 为什么会产生这种简单的想法? 那你至少应该给我点时间学一下吧? 不去培训你好歹给我点时间啊, 不用这么紧着问吧? 是不是非要让我说这个不难, 他们讲得也不好, 我自己就可以学会, 给我一点面子, 留点底裤啊. 我知道我不行, 我也知道你们一直在物质上支持着我, 但没必要什么都告诉你们吧? 彼此留点余地啊. 我去年就苦口婆心的告诉你们在外面消费很大, 你们不为所动, 以为几天几个星期就可以找到, 现在又要我会去, 我回不去了, 一两千块钱根本不够花, 我只能借钱, 现在欠了这么多, 我怎么回得去, 一个月还差不多一千块钱. 我没有本事还.

装猪的时间太长了, 都变成猪了.

这20天忙着伤春悲秋, 什么事情都没有做, 失策啊, 我为什么要听他们的呢? 现在好了,
决裂了, 我自己干!

父母对你, 大恩啊, 对于你来说, 大恩如大仇?

没有确切的进步路径--或者说抗拒这种确切的感觉, 更喜欢自由随心所欲的做, 没头苍蝇一样乱撞, 看似做了很多, 很快, 似乎很有效率, 但都打不倒七寸上, 没起到主要的作用, 没有明显的变化.

没用也没有必要的努力: 你都安装了那么多的源外deb软件包了, 再安装一个又如何呢? 为什么非要在安装Albert的时候尝试源码编译, 打包成appimage呢? 如果成功就算了, 但非但没有成功, 还浪费了大把的时间,这其实是没有用也没有必要的尝试. 这其实是不该用的努力. 你对什么东西都一无所知, 一个行外人去做专业人士才能做的事情. 而且这种事情对你产生不了一点价值. 即使成功带来的也是微不足道的优势. 太亏了.

盲干, 蛮干, 这是自由, 随心所欲做事情的特点. 或者说, 是必然.

不要将临时任务加到缓存中, 会忘记, 宁愿多出来也别存起来.
不能将精力一次性用光啊. 那样才是真正的浪费时间, 因为要花费很多时间来修养.

坐吃山空啊

只有一个任务，那就是生存
只有一个目标，那就是发展

2024.9.19-2024.10.21 这一个月你在干什么呢? 在配置软件? 什么软件这么重要值得你用一个月来配置? urxvt? 没有替代? LF? 难道不能使用? 你这一个月不止是浪费时间, 还在浪费金钱, 还在浪费机会. 一两千块钱, 足以出钱让人帮你配置好了, 你何必自讨苦吃? 这个月你做了很多事情, 但很多事情都没有产生价值.

你一直抱着一种侥幸心理啊, 学习是这样, 找工作也是这样. 没有人为你兜底的.



蜕去疯狂, 淫欲, 残暴的思想. 需要秩序和希望. 摆脱混乱和无序.

我从来没有想过搞Linux的配置会用去一个月四五十天, 今年在这以前最多也不过七八天而已. 我以为两三天就能解决的事情用了七八天近十天. 以后最少需要乘于3倍.

我应该在一来的时候就独立的, 那时候虽然什么都没有, 如果借钱, 我可以自己做事情, 大概还是可以用上几个月的, 当初没有决断, 现在到了这个地步, 无力回天.

我上个月有了决定之后是什么时候绝望的呢? 是知道花呗再也用不了的时候吧? 其实虽然计划不能实施, 但还是可以做很多事情的, 但我用配置来麻醉自己, 看小说不好, 没有目的的搞配置其实也是逃避.

要是2月分来的时候有一点决断, 现在也不会这么艰难, 现在人家在我身上投了那么多的钱, 自己在情在理上都不占优. 呜呼哀哉.

我何尝不知道他们的辛苦呢? 但我呢?

因为别人做的是大事, 即使只有一小步, 也会产生巨大的变化, 而我自己做的是小事, 即使做得再多, 也没有根本性的变化, 花费时间相同, 小事情耗费的精力甚至更多, 但就是没有什么正向的结果.

不是没有休息好, 不是生理的问题, 是思想精神的问题, 混乱, 无序, 甚至疯狂没有条理.


2024.11.16 以前想修好再走，看来行不通，得边走边修，边修边走

2024.11.26 两个月啊, 我怎么浪费了这么多的时间来做这些事情, 有些事情看着几分钟就能解决, 但正要解决, 怎么就需要几天的时间呢? 总是看着要做完了, 但就是做不完, 像是驴子头上的萝卜, 一直拉着你走, 勾引这你走. 唉, 应该学会拒绝诱惑, 学会责任, 学会什么是重要的, 什么是不重要的, 不能一切由着自己的性子来啊.

特别是对平铺窗口管理器这种东西, 需要做好, 不知道需要多少的时间.

2024.11.26 就像一个笑话, 这两个月来你敢了什么? 9月份你决定赌一把, 用一个月的时间来做准备找工作, 可你干了些什么呢? 你什么都没有做, 你除了配置所谓的效率软件之外, 你什么都没有做. 不做事情, 那里来谈效率呢? 两个月过去了, 还是现状.
2024.11.26 我以为我做这些事情几天就可以的, 甚至安装好就可以的,  但我确实没有想到, 自定义需要的时间这么多. 两个月啊, 我以为不用这么多的时间的. 我以为....
2024.11.26 一个月之前你就知道自己是个笑话了, 为什么不尝试着改变? 那天天很蓝啊, 跟今天一样, 记得很清楚啊. 为什么不改变, 像是着魔一样一头扎进来, 一来就是一个月?  为什么?
2024.11.26 我也没有想到, 消化人家的配置文件就用了10天, 太长了, 怎么能这么长?
我以为几天的事情甚至几个小时就可以做成的事情怎么就需要那么长的时间?
2024.11.26 找工作找了9个月, 但是招聘软件都没有打开过几次, 简直就是个笑话, 没钱了就骗父母, 再没钱了就贷款, 更是个笑话.
2024.11.26 我当初为什么要弄awesome? 好像是bspwm开机启动速度慢? awesome开机比较快一点? 现在想想可真搞笑, 那点时间够干什么? 浪费了就浪费了, 总比现在浪费了两个月的时间要好.
2024.11.26 费了这么多时间, 到底是因为这件事情本身就很难还是因为我本身比较差的缘故? 
2024.11.26 费了这么多的时间, 就为了做成这点事情, 其实是不值得的, 非常不值得的. 你所做的事情的投入产出比其实是非常低的. 仅仅为了用得舒服一点, 浪费10多天几个月, 这是非常非常不明智的. 这是非常非常不值得的, 如果你将这些时间来学习相关的知识, 那么做起来会舒服很多, 也会快很多, 这才是真正的高效. 像awesomewm, urxvt这样的东西, 不是为了初级用户而设计的 只看文档, 只看博客是不行的, 你必须知道很多东西, 明白很多预备知识才行. 如果初级用户非要来做这些事情, 那么必将付出沉重而惨烈的代价, 这两个月的时间就是证明, 你现在应该已经知道了.

2024.11.26 这样的生活就像是个深渊, 无休止的吞噬着我的时间, 金钱和精力.

2024.11.27 真不知道你怎么那么淡然的度过一天, 你沉迷于配置, 什么都不管不问, 现在, 报应来了, 你赌输了一切.
2024.11.27 九个月过去了, 什么都没有改变, 该不会的还是不会, 会的也忘记了. 和一年前两年前没有任何的变化, 至于bspwm和awesome, 你不觉得可笑么? 你可以说将它们配置的很好, 不说尽善尽美, 但可用性没得说. 但你浪费了多少时间, 多少钱? 你怎么就不吸取教训呢? Linux不是用来配置用来把玩的, 是用来干活的. 你不干活, 配置得高效又有什么用? 就awesomewm来说, 你在这个上面花费了两个月了, 房费, 生活费用了的钱有差不多6千了吧? 再算上今年花的钱, 两万! 可以买一个不错的Mac了, 为什么那么执着呢? 怪不得上个月那么急, 那是潜意识在提醒你, 在示警, 超时了, 但是你没有当成一回事, 总以为下一刻就做好了, 结果呢? 两个月. 现在清醒过来恨不得给自己两巴掌, 简直是昏了头了, 怎么会有这么愚蠢的行为? 我知道, 你很久就有了一种剑在头上的生活窘迫感, 但又无力改变, 但你不能就这样投降啊. 你应该跳起来给他一巴掌!
2024.11.27 你做事情没有决心, 犹犹豫豫, 过程中又瞻前顾后, 还不专一, 容易被别的东西吸引注意力, 有此下场, 实在是活该, 自作孽. 你当初来的时候就应该下定决心了, 不有那么多的来往. 3.9号事情发生, 你就应该收拾好心情, 做好打算, 哪怕绝望, 也好过躲在小说里面自暴自弃. 钱不够, 咬咬牙, 一口气贷款出来, 博一把, 胜利那不用愁, 失败也不会不甘心. 好过现在在这里自怨自艾.
2024.11.27 你在一个月之前几乎就有了结论, 一个人不可能配置一个系统的方方面面, 为什么不管不顾? 非要用最后一点生命时间来搞这些没有什么大用的东西?
2024.11.27 你在一个地方住的时间太长了, 足足半年, 这半年来你足不出户, 最远去过的地方不足一公里, 生于忧患, 死于安乐. 再加上你一直贷款, 就好像钱不知道哪里来的一样, 但你不知道这些钱, 总是要还的, 也总有一天, 人家不会再借给你的. 现在, 这一天, 来了. 
2024.11.27 你花费了这么大的代价, 不止是钱的代价, 还有时间的代价, 机会的代价, 配置了这么套东西, 也应该累了吧? 不要再换来换去的了, 既然花费了这么大的代价, 那就要将它们用到极致, 用到对得起自己配置的这一番苦心, 甚至用到它们再也用不了, 这才对得起自己所付出的一切. 不换了. 
2024.11.27 一直托, 一直拖, 拖到拖无可拖, 直到死期到来, 没有任何改变.
2024.11.27 不能一直借钱度日啊, 这无异于饮鸠止渴.
2024.11.27 很多事情, 不能因为害怕就不去想, 比如贷款, 比如工作, 比如配置需要花费的时间. 真的不去想, 不去管, 最坏, 最不能接受的结果就会出现.
2024.11.27 其实, 我感觉,而且还是很久之前就感觉, 不抽烟--这样就不会有依仗的感觉, 能冷静思考, 不听歌, 不看娱乐视频--这样就不会沉迷懈怠, 过着清苦的生活, 专注做一件事情, 那么效率才是最高, 脑子才是最清醒, 思路才是最严谨现实的. 

2024.11.27 其实, 你现在也应该知道, 你想做的事情是不可能的了吧?12月, 几乎不可能有什么像样的招聘了.  直到来年2月. 如果想要做, 那么这两个月, 应该挣够生活费, 房租, 应该还的贷款, 以及准备时间的生活费, 房租和应该还的贷款以及所有的一切花销. 那就应该找一个不管是多累的, 但钱多的工作. 不论什么工作.
找项目传上去, 投简历, 看看浪花怎么样.
未免期待拖延, 看看能不能借到钱. 借得到一两千的话, 那就完整做一下deque.hh, 否则的话就不做. 
真要准备, 那就要有豁出去的觉悟, 就不能东一榔头西一棒子的乱来, 必须系统的学习. 
错了就错了, 勇敢迈出第一步.
低端制造也是不能久留的. 可以暂时去做, 缓解生活压力, 但是不能作为生活的主业过多留恋
2024.11.27 你借钱维持了两个月的生活, 却从来没有想过这意味着什么, 每天得过且过, 一天消费小一百, 从没有想过, 如果再也借不到钱, 那么怎么活下去. 两个月啊, 我的天, 以前有监督, 想都不敢想, 现在, 居然一个配置就用了两个月, 几乎是6千, 我的天, 你在想什么? 你嘴上说的和实际做得, 完全不沾边啊, 你两个月没有写过哪怕一行C++代码啊. 你不是说这是一个赌吗? 你怎么一点都没沾到啊? 你上了赌桌, 然后扔下筹码去玩泥巴了? 光嘴上说, 然后手从来不动, 你是骗人骗到最后骗自己了? 你这是不要命了? 打算借完最后一笔贷款就去死? 看你慌张的样子, 也不像真要死啊.
目光如何短浅才能做出这种事情啊
2024.11.27 只要借来的钱能度日, 那就万事不管, 天啊, 怎么就活成了这个样子?
2024.11.27 应该有决断, 不能什么事情都往后拖, 一拖, 就不会再去想, 再去做了, 然后就会故意的回避, 直到末日的到来.
2024.11.27 贷款要干正事啊，如果没有发展，只是求存，无异于饮鸩止渴
2024.11.27 今年2月份来的时候给你两千, 就是让你来之后找到工作度过没有工资的那个月的, 就是让你一来尽快找到工作的, 直到现在, 母亲一直给你钱, 可以说很有情义了, 仁至义尽了. 给你钱, 自然是按照人家规划给的, 不可能按照你的想法来给你提供支持, 而且母亲在后来不是没有支持过你, 钱给足, 时间给足, 也就七八天问一下. 是你不争气, 辜负了她的期望, 还一直骗她, 以前可能不知道, 现在不知道也知道了. 你不能对她要求太多, 太过苛责, 不能怪她. 更多的应该怪你不争气. 你才是伤害她最深的人, 你伤害最深的人也是她. 你让母亲的支持成了一个笑话! 你让你母亲成了个笑话! 
你让母亲的期待成了个讽刺, 讽刺她连自己的儿子都看不明白. 你真该死啊!
2024.11.27 你贷款, 想给自己一个机会, 一个弥补自己的窗口, 其实这说不上错, 但你将这些钱用来干一些不相关的事情, 把时间浪费在毫无作用的事情上面, 这就是最大的错误了. 没有一点意识, 没有一点点危机感, 完全就是得过且过, 拿到钱就是玩, 这实在是... 或者说刚开始的时候确实有危机感的, 但时间一长, 着魔一样, 用了最多的时间, 精力来做看起来很容的事情, 以为明天或者下一刻就完成了, 但实际上, 永无尽头, 根本没有考虑过一个简单功能的时间需要花费多少时间, 值不值得, 更何况那么多功能, 定义出来的, 实现出来的, 用了多少呢? 配置, 你永远应该去做现在最急需的. 配置是永远做不完的, 自定义是没有尽头的, 一旦沉迷进去, 那就是浪费时间, 金钱, 生命了, 应该把握住一个度才好啊. 你想要一个用得舒服的环境, 这也没有错, 但是不应该这个时候, 这么关键的时候来做. 时间错位, 你做的事情没有任何效果, 还浪费了大好机会, 你确实是应该好好的静下心来想想了. 不能将一切错误归于别人, 很多人帮助过你, 但你辜负了他们的期望.
2024.11.27 遇到困难不要跑, 越跑越困难, 哪怕做错了, 也比不做好.
2024.11.27 其实我完全能理解了我为什么会沉迷配置. 我越是绝望, 越是没有把握, 就越是想放松一下, 小说不能看, 那么就做一下软件配置放松一下. 其实开始的时候就是想放松一下, 那时候确实有危机感, 紧张感, 但几分钟显然完成不了一个软件的全部配置, 越急越做不好, 越做不好越急. 只能用放松的心态来做, 但这就让我失去了对现实的感知, 失去了最为重要的危机感和紧张感. 我松弛了下来, 懈怠了下来. 忘记了我是有更重要的任务要做的, 忘记了我现在是贷款生活.

2024.11.28 Linux下的很多软件, 你要学就要学一整套操作流程, 比如gpg. 这个时候像博客这样的碎片化信息是不能胜任信息的需要的. 如果你想学会简单的操作, 就必须学会一套操作流程, 得不偿失. 简单明了的说明文档现在还没有看到过. 常用的操作说明也没有看到过. 常见的注意事项往往隐藏在一整篇的文章当中, 不显眼. 

2024.11.28 今天交通银行贷款10000元(壹万圆). 我现在每个月生活需要2500元(贰仟伍佰圆), 还贷1800元(壹仟捌佰圆). 一月总需2500+1800=4300元. 最多最多能支持两个月, 也就是说到1月25日. 所有的钱都会花光. 需要怎么做.
有一个想法, 就是开源节流, 节流没有地方可以节. 开源的话, 去做钟点工怎么样? 大部分时间学习, 投简历, 找工作, 到点的时候去打工.
           你需要注意的是, 你每个月花费4300元, 但不意味着你就可以无所顾忌的自己消费4300元, 你每个月只能消费2500元, 每天最好是只消费80元 . 而且如果出了意外, 贷款无法使用, 那么现状更加绝望.

2024.11.29 必须得承认, 我一点都不喜欢去干体力活, 工资还低, 但同时我真的没有一点把握在一个月内找到工作. 而且还是在这种时候. 而且, 这两年的学习经历告诉我, 在一个月内, 没有办法准备好.

2024.11.29 你完全不知道要做些什么, 两年前就是这样, 只想着先做, 没有一个具体的目标, 既不知道要做些什么, 也不知道人家需要什么, 没头苍蝇一样乱撞. 总想着先做, 目标后面决定,, 现在看来是一个错误的想法. 你不知道目标在哪里, 那么你就不知道方向朝哪边.

2024.11.29 你必须考虑到, 过年的时候虽然工人回家, 缺少人力, 但是很多商家也会关门回家过年, 需求岗位比现在更少.

2024.11.30 每个月都会崩溃, 然后看小说, 醒过来更加崩溃. 做点什么. 循环往复, 永无休止, 可悲可叹, 可怜可恨


2024.11.30 找工作找成了一个笑话, 不过相比人家上班反倒倒欠钱的人来说我还好, 都走到这一步了, 放宽心, 既然现在拿不定主意, 不知道怎么样好, 那先妥协, 那先抽半个月的时间, 写完项目, 投简历, 看看是否有涟漪.

2024.12.1 他们会考查些什么呢? 技术栈? 数据结构和算法? 网络?

2024.12.2 越是情况糟糕, 越应该克制自律, 而不是像末日狂欢般的放纵, 不论是以何种形式, 何种理由的放纵, 不论是看小说, 看娱乐视频, 搞电脑配置, 或者其他. 都没有做一点点正事来的重要. 你既不应该浪费时间, 也不应该浪费金钱, 没一快钱, 每一分时间, 都应该用在刀刃上.

2024.12.2 其实很容易知道你的时间浪费在了哪里, 小说, 你大部分时间都在看小说, 即使去除了两个月的配置时间, 你其实大部分时间都在看小说, 10月和11月并不都是在弄配置, 大概有20天的时间你都是再看小说, 今年总的看小说的时间加起来大概是有3个月的时间是在看小说的时间中的, 这才是你失败的元凶. 你努力的时间并没有你想的那么长. 克制住你看小说逃避现实的欲望, 人应该控制欲望而不是做欲望的奴隶, 你因该勇敢的面对现实.

2024.12.6 很多东西其实不要坚持, 要学会放弃, 比如有些小说, 其实没有必要去看完, 不要再做错误的事情.

2024.12.6 要是不该, 还是这样,  后果难料, 前途未卜

2024.12.6 最大的失败是没有去做

2024.12.6 失败的阴影如影随形, 我看不到一点希望, 只能坚持.

2024.12.6 要做些什么呢? 没时间了

2024.12.8 想要真正动起来, 那就不要想着得到什么, 做好什么都得不到的准备.

2024.12.10 2024.12.6号, 母亲问我天气转凉穿衣暖凉, 还给我转了1000块钱, 到这个地步, 我已经不敢告诉她实情了. 但四天又过去了. 我还是什么都没有做.

2024.12.12 我自己都对自己很绝望

2024.12.14 相信自己一次, 好吗? 相信自己一次吧.

2024.12.16 半个月过去了, 你在干什么? 你干了什么?

2024.12.17 17号了, 你干了什么? 你什么时候才能长大啊? 也许, 就业, 并不像你想像的那么难?
           你不是认为自己受到了小说的影响吗? 最好的解决方法就是面对它, <<斗破苍穹>>固然是不可畏,
           但是<<遮天>>也不值得信奉. 自从你看小说以来, 性格都变了, 整个人也变了, 人生也跟着变了,
           变得愤世嫉俗, 变得懒惰, 变得不再值得了.
           走了这么远, 步步坎坷, 步步带血, 该回过头来看看了.
           反思, 反省, 不能脑子空想. 以小说为例, 既然认为小说影响, 那么可以部分的看看小说,
           但只看小说是不行的,我看的小说够多了, 反倒越陷越深了, 需要对比, 需要别人来点醒你.
           需要考察任务人物的可笑幼稚的一面, 也要肯定他好的一面
           透过人物来视察自身. 很多小说里的东西, 一放在阳光下, 放在现实中,
           就现出原形了, 就成了一个不好意思跟别人提起来的笑话, 但需要注意的事情是, 过去的就过去了,
           这些事情再做一百遍也没有什么意义, 起不到任何的作用, 起个参考作用.
           再做其实意义也有限, 不过是求个心安, 给自己一个交代罢了. 
           [[https://www.bilibili.com/video/BV1sQqdYKEXL/][参考]]  [[/home/aeon/Videos/娱乐/萧炎难道就没缺点吗?BV1sQqdYKEXL.mkv][已下载]]

2024.12.18 需要的时候去学? 到时候不可能有时间的.
           书到用时方恨少. 就算能学,
           东一榔头西一棒子, 获取知识碎片化, 这是不行的. 最后还是要来补. 没有捷径
           一年了, 好像什么都没干好就过去了.
           两年了, 我做了什么? 什么都没有做? 青春年华!

2024.12.20 20号了, 你干了什么?
           你27岁了, 满周岁 

2024.12.24 快一个月了, 连开始都没有开始啊. 从未开始, 何来的结果

2024.12.25 只玩真实, 什么虚拟机, 什么测试, 一边去
2024.12.26 不能躲在虚拟世界里了
2024.12.29 我这一年就像是一个笑话一样
2024.12.30 很多事, 还没来得及, 就结束了. 不知道做了了什么, 不知道时间是怎么过去的. 恍恍惚惚又是一年

2025.1.4 就像是个笑话

2025.1.8 畏难, 畏难! 你要真有那个心, 该做的都做完了

* 没做的
vector 还没做逆向迭代器
list 还没做逆向迭代器

如果是需要做一个算法的头文件, 那么在此文件建议重写rand(), openbsd编译vector发出警告, 试着解决, gcd是需要写的STL和我所看得没有什么不同.
可以看看N!阶乘的算法, 看看能不能加进去:
[[https://blog.csdn.net/ppj040857/article/details/83913278#:~:text=%E6%9C%AC%E4%B8%BB%E9%A2%98%E8%81%9A%E7%84%A6%E4%BA%8E%E4%BD%BF%E7%94%A8C%E8%AF%AD][N！阶乘的高效算法-CSDN博客]]
[[https://blog.csdn.net/shenzhenhair/article/details/8615372#:~:text=%E5%BE%88%E5%A4%9A%E5%85%AC%E5%8F%B8%E9%9D%A2%E8%AF%95%E9%83%BD%E4%BC%9A%E6%9C%89%E4%B8%80][关于N的阶乘(n!)的java算法实现_任务二 阶乘计算功能实现n!功能。其中n小于10。public long factorial(i-CSDN博客]]

lldb太丝滑了, 我艹, 简直就是种享受. 我去, 太舒服了. 简直就是华丽, 像是个美女一样, 皮肤细腻白皙, 一头长长的头发. 我去, 享受!
